#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

# Run make
#==============================================
echo "Running Make ..."
if ! make; then
	echo "Error occured while Compilation proccess, check what are You Pushing PLS!!!"
	echo "Your Push is 💩 - it is aborted"
	exit 1
fi
# Test your code 
#==============================================
# echo "Running make check..."
# if ! make check; then
# 	echo "Error occured while Testing proccess, check what are You Pushing PLS!!!"
# 	echo "Your Push is 💩 - it is aborted"
#     exit 1
# fi

echo "All checks passed. Proceeding with push. GOOD JOB!"

exit 0
